%module PyMeshUtils
%include numpy_setup.i
%include EigenTypedef.i
%include eigen.i
%include ExceptionConverter.i
%include AttributeUtils.i
%include TriangleMetric.i
%include ObtuseTriangleRemoval.i
%include ShortEdgeRemoval.i
%include MeshUtils.i
%include MeshSeparator.i
