%module PyMeshUtils
%include numpy_setup.i
%include Core/EigenTypedef.i
%include eigen.i
%include Core/ExceptionConverter.i
%include AttributeUtils.i
%include TriangleMetric.i
%include ObtuseTriangleRemoval.i
%include ShortEdgeRemoval.i
%include MeshUtils.i
%include MeshSeparator.i
%include Boundary.i
