%module PyAssembler
%include numpy_setup.i
%include Core/EigenTypedef.i
%include eigen.i
%include Core/ExceptionConverter.i
%include Math/ZSparseMatrix.i
%include Mesh.i
%include Materials/Material.i
%include FEAssembler.i
