%module PyMesh
%include ExceptionConverter.i
%include numpy_setup.i
%include eigen.i
%include EigenTypedef.i
%include Mesh.i
%include MeshFactory.i
%include MeshWriter.i
%include OBJWriter.i
%include HashGrid.i
