# MKL
IF (NOT MKL_FOUND)
    FIND_PACKAGE(MKL)
ENDIF (NOT MKL_FOUND)

# Include Eigen
IF (NOT EIGEN_FOUND)
    FIND_PACKAGE(Eigen REQUIRED)
ENDIF (NOT EIGEN_FOUND)

# TBB
IF (NOT TBB_FOUND)
    SET(TBB_ROOT ${PROJECT_SOURCE_DIR}/python/pymesh/third_party/)
    FIND_PACKAGE(TBB REQUIRED)
ENDIF (NOT TBB_FOUND)

# SpraseHash
IF (NOT SPARSEHAHS_FOUND)
    FIND_PACKAGE(SparseHash QUIET)
ENDIF (NOT SPARSEHAHS_FOUND)

# GMP
IF (NOT GMP_FOUND)
    FIND_PACKAGE(GMP QUIET)
ENDIF (NOT GMP_FOUND)

# MPFR
IF (NOT MPFR_FOUND)
    FIND_PACKAGE(MPFR QUIET)
ENDIF (NOT MPFR_FOUND)

# CGAL
IF (NOT CGAL_FOUND)
    SET(CGAL_DIRS
        "${PROJECT_SOURCE_DIR}/python/pymesh/third_party/lib/cmake/CGAL"
        "${PROJECT_SOURCE_DIR}/python/pymesh/third_party/lib64/cmake/CGAL"
    )
    SET(CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE TRUE)
    IF (NOT Boost_FOUND)
        SET(BOOST_ROOT ${PROJECT_SOURCE_DIR}/python/pymesh/third_party)
        FIND_PACKAGE(Boost COMPONENTS atomic chrono date_time system thread)
    ENDIF (NOT Boost_FOUND)
    FIND_PACKAGE(CGAL QUIET PATHS ${CGAL_DIRS} NO_DEFAULT_PATH)
ENDIF (NOT CGAL_FOUND)

# MMG
IF (NOT Mmg_FOUND)
    IF (DEFINED ENV{MMG_PATH})
        SET(MMG_BUILD_DIR $ENV{MMG_PATH})
    ELSE (DEFINED ENV{MMG_PATH})
        SET(MMG_BUILD_DIR ${PROJECT_SOURCE_DIR}/python/pymesh/third_party/)
    ENDIF (DEFINED ENV{MMG_PATH})
    FIND_PACKAGE(Mmg QUIET)
ENDIF ()

# Qhull
IF (NOT QHULL_FOUND)
    SET(QHULL_USE_STATIC TRUE)
    IF (DEFINED ENV{QHULL_PATH})
        SET(QHULL_ROOT $ENV{QHULL_PATH})
    ENDIF (DEFINED ENV{QHULL_PATH})
    FIND_PACKAGE(Qhull QUIET)
ENDIF (NOT QHULL_FOUND)

# Quartet
IF (NOT QUARTET_FOUND)
    FIND_PACKAGE(Quartet QUIET)
ENDIF (NOT QUARTET_FOUND)

# Triangle
IF (NOT TRIANGLE_FOUND)
    FIND_PACKAGE(Triangle QUIET)
ENDIF (NOT TRIANGLE_FOUND)

# Tetgen
IF (NOT TETGEN_FOUND)
    FIND_PACKAGE(Tetgen QUIET)
ENDIF (NOT TETGEN_FOUND)

# Cork
IF (NOT CORK_FOUND)
    FIND_PACKAGE(Cork QUIET)
ENDIF(NOT CORK_FOUND)

# Clipper
IF (NOT CLIPPER_FOUND)
    FIND_PACKAGE(Clipper QUIET)
ENDIF (NOT CLIPPER_FOUND)

# libigl
IF (NOT libigl_FOUND)
    FIND_PACKAGE(libigl QUIET)
ENDIF ()

# Carve
IF (NOT Carve_FOUND)
    FIND_PACKAGE(Carve QUIET)
ENDIF ()

# BSP
IF (NOT BSP_FOUND)
    FIND_PACKAGE(BSP QUIET)
ENDIF (NOT BSP_FOUND)

# SuiteSparse
IF (NOT Umfpack_FOUND)
    FIND_PACKAGE(Umfpack QUIET)
ENDIF ()

# Cholmod
IF (NOT Cholmod_FOUND)
    FIND_PACKAGE(Cholmod QUIET)
ENDIF ()

# Metis
IF (NOT Metis_FOUND)
    FIND_PACKAGE(Metis QUIET)
ENDIF ()

# tinyxml2
IF (NOT TINYXML2_FOUND)
    FIND_PACKAGE(tinyxml2 QUIET)
ENDIF (NOT TINYXML2_FOUND)

# Lapack
IF (NOT LAPACK_FOUND)
    FIND_PACKAGE(LAPACK QUIET)
ENDIF (NOT LAPACK_FOUND)

# Geogram
IF (NOT GEOGRAM_FOUND)
    SET(GEOGRAM_INSTALL_PREFIX ${PROJECT_SOURCE_DIR}/python/pymesh/third_party)
    FIND_PACKAGE(Geogram QUIET)
ENDIF (NOT GEOGRAM_FOUND)

# Draco
IF (NOT draco_FOUND)
    FIND_PACKAGE(Draco QUIET)
ENDIF (NOT draco_FOUND)

# TetWild
IF (NOT TetWild_FOUND)
    FIND_PACKAGE(TetWild QUIET)
ENDIF ()

# Fast winding number
IF (NOT FastWindingNumber_FOUND)
    FIND_PACKAGE(FastWindingNumber QUIET)
ENDIF ()

IF (NOT Jigsaw_FOUND)
    FIND_PACKAGE(Jigsaw QUIET)
ENDIF ()
